### ISSUE TITLE
Can't generate Appx with Sign 

### ISSUE THREAD

**Issue by poumason** [pwa-builder/ManifoldJS#311]
I can use pwabuilder to generate Appx for Windows 10.
If I want to test appx on Xbox, the appx must be signed.
So I use the command: `pwabuilder.cmd package myAppx -p windows10 -S`
But CloudAppx response failed message:  `The CloudAppX service returned an error - Not Found (404): Cannot POST /v3/buildsigned`
I don't know the message.
```
[debug] pwabuilder  : Available platforms within project: windows10
[debug] pwabuilder  : Packaging the following platforms: windows10
[debug] pwabuilder  : Loading platform module: pwabuilder-windows10
[debug] pwabuilder  : Packaging the 'Windows 10 Platform' app...
[info ] windows10   : The Windows 10 Platform app received a Sign flag and will be signed by CloudAppx!
[info ] windows10   : Packaging the Windows 10 Platform app...
[debug] pwabuilder  : Invoking the CloudAppX service to generate a signed APPX package
[debug] pwabuilder  : Invoking the CloudAppX service...
[error] pwabuilder  : Failed to package the Windows 10 Platform app.
                          at C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\pwabuilder-lib\lib\projectBuilder.js:198:31
                          at _rejected (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:864:24)
                          at C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:890:30
                          at Promise.when (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:1142:31)
                          at Promise.promise.promiseDispatch (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:808:41)
                          at C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:624:44
                          at runSingle (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:137:13)
                          at flush (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:125:13)
                          at _combinedTickCallback (internal/process/next_tick.js:131:7)
                          at process._tickCallback (internal/process/next_tick.js:180:9)
                      Failed to create the package. The CloudAppX service returned an error - Not Found (404): Cannot POST /v3/buildsigned

                          at Request._callback (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\pwabuilder-windows10\lib\appPackage.js:73:32)
                          at Request.self.callback (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\pwabuilder-windows10\node_modules\request\request.js:185:22)
                          at emitTwo (events.js:126:13)
                          at Request.emit (events.js:214:7)
                          at Request.<anonymous> (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\pwabuilder-windows10\node_modules\request\request.js:1157:10)
                          at emitOne (events.js:116:13)
                          at Request.emit (events.js:211:7)
                          at IncomingMessage.<anonymous> (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\pwabuilder-windows10\node_modules\request\request.js:1079:12)
                          at Object.onceWrapper (events.js:313:30)
                          at emitNone (events.js:111:20)
[error] pwabuilder  : One or more platforms could not be generated successfully.
                          at C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\pwabuilder-lib\lib\projectBuilder.js:29:23
                          at _fulfilled (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:854:54)
                          at self.promiseDispatch.done (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:883:30)
                          at Promise.promise.promiseDispatch (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:816:13)
                          at C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:624:44
                          at runSingle (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:137:13)
                          at flush (C:\Users\pouma\AppData\Roaming\npm\node_modules\pwabuilder\node_modules\q\q.js:125:13)
                          at _combinedTickCallback (internal/process/next_tick.js:131:7)
                          at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by boyofgreen** [comment]
Yes, the sign tool is blocked by azure, so we can't run it.  However we do generate the pri file, so for the xbox you can laod it as a loose package within the portal page.  There are some instructions within the blog post (hwa  = pwa , manifoldjs = pwabuilder) :)
https://blogs.windows.com/buildingapps/2016/09/30/uwp-hosted-web-app-on-xbox-one-app-dev-on-xbox-series/#9UuHrTtDdlRcRYZc.97

thanks!

**Comment by poumason** [comment]
Thank your response.
I already solve it, but I forget to close the issue.
I use SignTool.exe to add SHA into the appx, such as:

```
cd "C:\Program Files (x86)\Windows Kits\10\bin\x86\"
SignTool sign /fd SHA256 /a /f "C:\myApp\PWA\Store packages\windows10\package\App1_StoreKey.pfx" "C:\myApp\PWA\Store packages\windows10\package\windows.appx"
```

App1_StoreKey.pfx must be use VS2017 to create it with associate Project of Dev Center.
